### ISSUE TITLE
USER STORY: login

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/online-shopping-simulator#1]
In order to **access the website** as a **user**, I can **click the login button**
### Acceptance Criteria:
- login button only displays when user is not logged in
- available in more than one place
- eye catching and obvious to the user
### Tasks:
- [x] import django allauth
- [ ] add button to navbar
- [x] add button to homepage
