### ISSUE TITLE
USER STORY: add to cart

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/online-shopping-simulator#13]
As a site user I can add items to a cart so that I can subsequently buy them using click and collect.
### Acceptance Criteria:
- keep it clear to the customer of what they are doing
- notifications when item added to cart
- store order history
### Tasks:
- [ ] cart model
- [ ] order history model
- [ ] cart view
- [ ] click and collect view (this might remove items cart and archive them to order history)
- [ ] urls
- [ ] cart template
- [ ] order history template
- [ ] add to cart button
- [ ] view cart button
- [ ] order history button
- [ ] notifications
