### ISSUE TITLE
USER STORY: logout

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/online-shopping-simulator#2]
In order to **prevent my account from being left open** as a **user**, I can **click the logout button**
### Acceptance Criteria:
- only display when user is logged in
- eye catching and easy to find
### Tasks:
- [x] link to allauth
- [x] add button to navbar
- [x] add button to homepage
