### ISSUE TITLE
USER STORY: create an account

### ISSUE THREAD

**Issue by MarkChips** [MarkChips/online-shopping-simulator#3]
In order to **create an account** as a **user**, I can **click the register button**
### Acceptance Criteria:
- Only display when user is not logged in
- eye catching and easy to find
### Tasks:
- [x] connect to allauth template
- [x] add button to navbar
- [x] add button to homepage
