### ISSUE TITLE
USER STORY: Delete My Account

### ISSUE THREAD

**Issue by SteveBenton6** [MarkChips/online-shopping-simulator#8]
In order to **update account settings** as a **user**, I want to delete my account **so that my personal data is no longer stored.**
### Acceptance Criteria:
- [ ] AC1 - Option provided to registered user, to delete account.
- [ ] AC2 - Deletion is validated with multiple steps to prevent accidental deletion.
- [ ] AC3 - When deleted, all related personal data is deleted from the databases and system.
### Tasks:
- [ ] task
